clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
branches:
  only:
    - master
dotnet_csproj:
  patch: true
  file: 'LyricMaker.Tests\LyricMaker.Tests.csproj' # Use wildcard when it's able to exclude Xamarin projects
  version: '0.0.{build}'
cache:
  - '%LOCALAPPDATA%\NuGet\v3-cache -> appveyor.yml'
before_build:
  - ps: dotnet --info # Useful when version mismatch between CI and local
  - ps: nuget restore -verbosity quiet # Only nuget.exe knows both new (.NET Core) and old (Xamarin) projects
build:
  project: LyricMaker.sln
  parallel: true
  verbosity: minimal
after_build:
  - ps: dotnet tool restore
test:
  assemblies:
    except:
      - '**\*Android*'
      - '**\*iOS*'
      - 'build\**\*'
